name: clone
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.8.0
  flutter_tts: ^4.2.1
  speech_to_text: ^7.0.0
  http: ^0.13.0
  google_fonts: ^4.0.4
  lottie: ^3.0.0
  flutter_riverpod: ^2.3.6
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  uuid: ^4.5.1
  timeago: ^3.5.0
  file_picker: ^8.1.7
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  google_ml_kit: ^0.19.0
  google_mlkit_commons: ^0.9.0
  flutter_sound: ^9.2.13
  fl_chart: ^0.69.2
  path: ^1.8.3
  path_provider: ^2.1.1
  image: ^4.1.3
  pdf_text: ^0.5.0
  mime: ^2.0.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
